### PR TITLE
UI layout change

### PR DESCRIPTION
**Pull request by hjyssg**
1. resize_console() removed
2. use css
image

### CODE REVIEW

**Review by romanvm — CHANGES_REQUESTED** [review]
1. Please fix the CI error (ESLint).
2. I see 2 problems with the new layout:
    * The right edges of variables windows are not aligned with the console window and the code  window (in narrow viewports).
    * There is no margin below the console input field.

See the screenshot:
image

**Comment by hjyssg** [comment]
Where can I see the CI error (ESLint)? 
I did not found it in https://travis-ci.org/github/romanvm/python-web-pdb/pull_requests

**Comment by romanvm** [comment]
That is strange because the failed CI checks can be found on this very page and by your link as well.

**Comment by romanvm** [comment]
I'm closing this because there's haven't been any updates for some time.

**Pull request closed without merging**
