### PR TITLE
Allow using a different PrismJS Theme

### PR DESCRIPTION
**Pull request by cb109**
I have added support to choose from the builtin PrismJS Themes, with Okaidia still being the default. Technically it works by serving the css files for each and then adjusting the link.href dynamically when a theme is chosen, which is the same thing the https://prismjs.com/ website is doing.

Peek 2022-01-07 15-02

Let me know your thoughts, if this is something you could imagine to merge. I tried following existing coding conventions, but am happy to change anything if it helps adoption. I would also love to "remember" the chosen theme e.g. in localStorage, but since that's not done yet for anything else I thought I'd ask first.

Thank you for the tool, I :heart: it.

### CODE REVIEW

**Comment by romanvm** [comment]
Thanks, I'll check it. BTW, you should add your name in the copyright notice of the new .js file.

**Comment by cb109** [comment]
No idea why the 3.10 tests fail, as I haven't touched any of the backend, maybe you can have a look as currently it's not possible for me to easily test 3.10 on my machine :bow:

**Comment by romanvm** [comment]
Regarding the failing 3.10 test, it's a know issue that I haven't been able to resolve yet. I guess I need to mark this test as skipped until I have enough time to investigate it.

**Comment by romanvm** [comment]
Sorry for the late reply. I've checked your PR. Looks intetesting. The only minor issue that I've noticed is that a mouse cursor inside the theme selection dropdown is a textual one (a vertical line) instead of a pointer (an arrow). Could you check this?

**Comment by cb109** [comment]
Good catch, I did not notice that. It was because I did not use any `href` on the anchors and bootstrap 3 styles them a little differently then. It is [probably debatable ](https://stackoverflow.com/questions/134845/which-href-value-should-i-use-for-javascript-links-or-javascriptvoid0)whether for javascript-anchors a `href="#"` or `href="javascript:void(0)"` or just omitting it and using some additional css is the best approach, I picked the latter for now. Let me know if there is more I can do 👋

**Comment by cb109** [comment]
I'm having some trouble fixing the conflicts, likely cause I am using a different nodejs version to run the npm dependency solver and build command (node 17.x seems bugged on windows, had to downgrade to 16.x). What nodejs and npm versions are you using exactly? Maybe using the same version and running the commands again will fix it.

**Comment by romanvm** [comment]
Could you merge the current master into this? FYI: I'm using node v16.17.0 with the latest changes.

**Comment by cb109** [comment]
@romanvm I did my best to resolve all conflicts, on my side the build looks good, using the same node version as you v16.17.0. I have added all build artifacts from the frontend to git, which means the themes are there as well, I hope that was correct. I would love to add that the web UI "remembers" my last theme choice, maybe via `localStorage`, what do you think?

**Comment by romanvm** [comment]
Hi. I'm sorry but I have to respectfully decline your PR. Currently I have very little time and resources to maintain this project and I don't wan't to introduce additional complexity that do not affect core functionality.

**Comment by cb109** [comment]
Hi Roman, not a problem at all. Stay safe 🫂

**Pull request closed without merging**
