### PR TITLE
Feature/UI layout update

### PR DESCRIPTION
**Pull request by dhvcc**
Hi, this is a fix/enhancment of #29 

My changes are:
- Media queries
- Painted repl input so it's noticeable
- Moved toolbar to navbar to save space

A screenshot of 1920x937 inner height window

image

### CODE REVIEW

**Comment by romanvm** [comment]
Thank you for your contribution. I'll check the PR and update accordingly.

**Comment by romanvm** [comment]
Movind the toolbar to the navbar area is a sound idea but media queries don't do a good job of dynamically adjusting the UI while the browser window is being resized. I'll post videos later if needed.

**Comment by dhvcc** [comment]
Hey, any updates on your decision? Thanks!

**Comment by romanvm** [comment]
Sorry, I had no time to re-test this one because of the real life stuff. I'll try to do this as soon as I can.

**Comment by dhvcc** [comment]
No worries mate, just wanted to check this out is not abandoned. This is not urgent, take care and be safe

**Comment by romanvm** [comment]
I've finally found some time to work on this project. Could you merge the current master into this and resolve possible conflicts?

**Comment by dhvcc** [comment]
Seems like there's an issue with builds on master

**Comment by romanvm** [comment]
I have fixed GH pipelines on master. Please merge again.

**Comment by dhvcc** [comment]
Not sure if you've seen it, but I pushed new commits, you can start a workflow, @romanvm 👍

**Comment by romanvm** [comment]
I've tested your PR again. The idea to move the button bar to the top is a good one. But media queries do terrible job of adjusting the debugger UI to the browser's viewport compared to my initial solution. So I'm afraid I cannot accept this PR as it is now. I see 2 options:

a) you leave only the part about the button bar and restore the initial method of resizing the debugger UI;

b) you improve your resizing method (if it's possible).

I admit that my frontend skills are limited and my solution for auto-resizing the debugger UI may not be an optimal one but it does the job.

**Comment by dhvcc** [comment]
@romanvm Hi, I agree that media queries are terrible, guess I just wanted to do a quick hack. Let me see if I can come up with something better than this.

**Comment by dhvcc** [comment]
@romanvm quickly hacked a new layout using css grid, heres the showcase. It may still not work idealy on really smal screens where title wraps into 2 lines. This is not the issue of this PR, but of the the way it's coded. I might revisit this and fix this one also. Don't close this PR so I can push here. But yeah, may be give this update a review and some feedback
image

**Comment by romanvm** [comment]
Thanks. I'll check it as soon as I can considering all the circumstances.

**Comment by dhvcc** [comment]
Hi, revisiting this stale PR. Do I need to sync the new branch to be reviewed?

**Comment by romanvm** [comment]
Hi. No need to do anything at the moment. I was busy with my life matters for quite a while but hopefully I will be able to address pending PRs soon.

**Comment by dhvcc** [comment]
> Hi. No need to do anything at the moment. I was busy with my life matters for quite a while but hopefully I will be able to address pending PRs soon.

Sure, no pressure, be safe and well, was just wondering around my PRs

**Comment by romanvm** [comment]
Now the UI is totally broken: it's bigger than browser's viewport with horisontal and vertical scrollbars. And this is on 1920x1080 monitor resolution. The horizontal sizing is especially bad: if a variable is a collection with many members then the UI is stretched very wide.

image


I'm afraid I have to respectfully decline this PR. My time for maintaining this project is limited so I want to focus only on maintaining compatibility with current Python version and fixing bugs if any found, so I'd rather not to introduce additional complexity.

**Comment by dhvcc** [comment]
Ok sure, I'll fix it in my fork and leave it there 👋

**Pull request closed without merging**
